name: Update STB
on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 1/16 * *"
permissions:
  contents: read

jobs:
  updateSTB:
    permissions:
      contents: write 
      pull-requests: write
    if: ${{ github.repository == 'mlpack/mlpack' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Latest STB Tagged Releases
        id: stb-header
        run: |
          # Fetch latest release information for both stb_image.h and stb_image_write.h
          STB_IMAGE_RELEASE_JSON=$(curl -sL https://api.github.com/repos/nothings/stb/releases/tags/stb_image.h)
          STB_IMAGE_WRITE_RELEASE_JSON=$(curl -sL https://api.github.com/repos/nothings/stb/releases/tags/stb_image_write.h)

          # Extract the latest versions for both headers (example versions 2.30 and 1.16 as per the request)
          STB_IMAGE_RELEASE_VERSION=$(jq -r ".tag_name" <<< "$STB_IMAGE_RELEASE_JSON" | tr -d 'v')
          STB_IMAGE_WRITE_RELEASE_VERSION=$(jq -r ".tag_name" <<< "$STB_IMAGE_WRITE_RELEASE_JSON" | tr -d 'v')

          echo "stb_image_release_version=${STB_IMAGE_RELEASE_VERSION}" >> $GITHUB_OUTPUT
          echo "stb_image_write_release_version=${STB_IMAGE_WRITE_RELEASE_VERSION}" >> $GITHUB_OUTPUT

          # Extract the current versions from the version text files
          CURRENT_IMAGE_VERSION=$(grep -Po "stb_image.h version: \K\d+\.\d+" src/mlpack/bindings/stb/third_party/STB/stb_image_version.txt || echo "0.0")
          CURRENT_IMAGE_WRITE_VERSION=$(grep -Po "stb_image_write.h version: \K\d+\.\d+" src/mlpack/bindings/stb/third_party/STB/stb_image_write_version.txt || echo "0.0")

          echo "current_image_version=${CURRENT_IMAGE_VERSION}" >> $GITHUB_OUTPUT
          echo "current_image_write_version=${CURRENT_IMAGE_WRITE_VERSION}" >> $GITHUB_OUTPUT

      - name: Update STB Image Header
        if: steps.stb-header.outputs.current_image_version != steps.stb-header.outputs.stb_image_release_version
        env:
          IMAGE_RELEASE_TAG: ${{ steps.stb-header.outputs.stb_image_release_version }}
          CURRENT_IMAGE_TAG: ${{ steps.stb-header.outputs.current_image_version }}
        run: |
          # Download updated stb_image.h if versions are different
          curl -sL https://github.com/nothings/stb/releases/download/v${IMAGE_RELEASE_TAG}/stb_image.h -o src/mlpack/bindings/stb/third_party/STB/stb_image.h

          # Update the version file for stb_image.h
          echo "stb_image.h version: ${IMAGE_RELEASE_TAG}" > src/mlpack/bindings/stb/third_party/STB/stb_image_version.txt

      - name: Update STB Image Write Header
        if: steps.stb-header.outputs.current_image_write_version != steps.stb-header.outputs.stb_image_write_release_version
        env:
          IMAGE_WRITE_RELEASE_TAG: ${{ steps.stb-header.outputs.stb_image_write_release_version }}
          CURRENT_IMAGE_WRITE_TAG: ${{ steps.stb-header.outputs.current_image_write_version }}
        run: |
          # Download updated stb_image_write.h if versions are different
          curl -sL https://github.com/nothings/stb/releases/download/v${IMAGE_WRITE_RELEASE_TAG}/stb_image_write.h -o src/mlpack/bindings/stb/third_party/STB/stb_image_write.h

          # Update the version file for stb_image_write.h
          echo "stb_image_write.h version: ${IMAGE_WRITE_RELEASE_TAG}" > src/mlpack/bindings/stb/third_party/STB/stb_image_write_version.txt

      - name: Create Pull Request for STB
        if: steps.stb-header.outputs.current_image_version != steps.stb-header.outputs.stb_image_release_version || steps.stb-header.outputs.current_image_write_version != steps.stb-header.outputs.stb_image_write_release_version
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Upgrade STB to versions ${{ steps.stb-header.outputs.stb_image_release_version }} and ${{ steps.stb-header.outputs.stb_image_write_release_version }}
          title: Upgrade STB to versions ${{ steps.stb-header.outputs.stb_image_release_version }} and ${{ steps.stb-header.outputs.stb_image_write_release_version }}
          body: |
            Updates [nothings/stb](https://github.com/nothings/stb) to versions ${{ steps.stb-header.outputs.stb_image_release_version }} (stb_image.h) and ${{ steps.stb-header.outputs.stb_image_write_release_version }} (stb_image_write.h).
            Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request).
          labels: update dependencies, automated PR
          branch: stb-header-updates-${{ steps.stb-header.outputs.stb_image_release_version }}-${{ steps.stb-header.outputs.stb_image_write_release_version }}
